language: go

go:
  - 1.4

# I know I like my dependencies specified by custom meta tags in HTML!
# Oh wait, no. No I don't.
install: true

script:
  - ./goad init
  - ./goad validate
  - ./goad test
  - ./goad install
